15.2

diff --git a/src/tools/make_etags b/src/tools/make_etags
--- a/src/tools/make_etags
+++ b/src/tools/make_etags
@@ -1,12 +1,16 @@
 #!/bin/sh
 
-# src/tools/make_etags [-n]
+# src/tools/make_etags
 
-if [ $# -gt 1 ] || ( [ $# -eq 1 ] && [ $1 != "-n" ] )
-then	echo "Usage: $0 [-n]"
-	exit 1
-fi
+command -v etags >/dev/null || \
+	{ echo "'etags' program not found" 1>&2; exit 1; }
 
-cdir=`dirname $0`
-dir=`(cd $cdir && pwd)`
-exec $dir/make_ctags -e $*
+rm -f ./TAGS
+
+find `pwd`/ -type f -name '*.[chyl]' -print |
+	xargs etags --append -o TAGS
+
+find . \( -name CVS -prune \) -o \( -name .git -prune \) -o -type d -print |
+while read DIR
+do	[ "$DIR" != "." ] && ln -f -s `pwd`/TAGS "$DIR"
+done
